#!/usr/bin/env python3
"""Generate fully populated D3D12 vtables from the real d3d12.h.

The design is explicit that this must use generated interfaces rather than
hand-built partial vtables, and the reason is practical: a partially filled
vtable leaves NULL slots, and calling one is a jump to address zero rather than
a diagnosable E_NOTIMPL. A game that probes an unimplemented method should get a
clean refusal and a named log line, not a crash we then have to symbolise.

So every slot in every interface gets a typed stub with the correct signature.
Real implementations are written by hand and override individual slots at
construction, which keeps the "what is actually supported" list short, explicit
and greppable instead of implied by which slots happen to be non-NULL.

Usage:  gen_vtables.py <path to d3d12.h> <output header>
"""
import re
import sys

# Interfaces the runtime currently constructs. Adding one here is all that is
# needed to get its stub table; implementing methods stays a separate, deliberate act.
INTERFACES = [
    "ID3D12Device10",   # ml877: the device answers ID3D12Device1..8; a UE 5.4 title fatals without Device1/Device2
    "ID3D12CommandQueue",
    "ID3D12CommandAllocator",
    "ID3D12GraphicsCommandList7",   # ml1144: the list answers GraphicsCommandList1..7; a UE 5.0 title fatals when List4 is refused
    "ID3D12Fence",
    "ID3D12Resource2",   # ml886: Resource1/Resource2 queries must not fail silently
    "ID3D12RootSignature",
    "ID3D12PipelineState",
    "ID3D12DescriptorHeap",
]

# Return types that are not HRESULT need their own "harmless zero" expression.
ZERO_RETURNS = {
    "void": None,
    "ULONG": "0",
    "UINT": "0",
    "UINT64": "0",
    "D3D12_GPU_VIRTUAL_ADDRESS": "0",
    "LUID": "zero",
    "D3D12_RESOURCE_DESC": "zero",
    "D3D12_HEAP_PROPERTIES": "zero",
    "D3D12_COMMAND_LIST_TYPE": "(D3D12_COMMAND_LIST_TYPE)0",
    "D3D12_CPU_DESCRIPTOR_HANDLE": "zero",
    "D3D12_GPU_DESCRIPTOR_HANDLE": "zero",
}

METHOD_RE = re.compile(
    r"([A-Za-z_][\w \t\*]*?)\s*\(\s*STDMETHODCALLTYPE\s*\*\s*(\w+)\s*\)\s*\(\s*(.*?)\)\s*;",
    re.S,
)


def parse(header_text, iface):
    m = re.search(
        r"typedef struct " + iface + r"Vtbl \{(.*?)\} " + iface + r"Vtbl;",
        header_text,
        re.S,
    )
    if not m:
        raise SystemExit("vtable for %s not found" % iface)
    body = m.group(1)
    out = []
    for ret, name, args in METHOD_RE.findall(body):
        ret = " ".join(ret.split())
        # Normalise whitespace but keep parameter names: they become the stub's
        # own parameter list verbatim, so the signature cannot drift.
        arglist = " ".join(args.split())
        out.append((ret, name, arglist))
    return out


def emit(header_path, out_path):
    text = open(header_path, errors="ignore").read()
    L = []
    L.append("/* GENERATED by src/pe/gen_vtables.py from d3d12.h -- do not edit by hand.")
    L.append(" *")
    L.append(" * Every vtable slot is filled with a typed stub, so an unimplemented method")
    L.append(" * returns E_NOTIMPL and names itself instead of jumping through a NULL slot.")
    L.append(" * Implemented methods are assigned over these at construction. */")
    L.append("#ifndef MADEIRA_D3D12_STUBS_H")
    L.append("#define MADEIRA_D3D12_STUBS_H")
    L.append("")
    L.append("#include <d3d12.h>")
    L.append("")
    L.append("/* Names every refusal once, so a game probing an unsupported method leaves a")
    L.append(" * trail instead of silently taking a fallback path. */")
    L.append("void madeira_d3d12_note_unimplemented(const char *iface, const char *method);")
    L.append("")
    L.append("/* ml1143: private data is really stored, per object and GUID (madeira_d3d12.c). */")
    L.append("static HRESULT mad_pd_get(const void *obj, REFGUID guid, UINT *data_size, void *data);")
    L.append("static HRESULT mad_pd_set(const void *obj, REFGUID guid, UINT data_size, const void *data);")
    L.append("static HRESULT mad_pd_set_iface(const void *obj, REFGUID guid, const IUnknown *data);")
    L.append("")

    for iface in INTERFACES:
        methods = parse(text, iface)
        L.append("/* ---- %s: %d slots ---- */" % (iface, len(methods)))
        for ret, name, args in methods:
            fn = "stub_%s_%s" % (iface, name)
            L.append("static %s STDMETHODCALLTYPE %s(%s) {" % (ret, fn, args))
            # Private data: every object keeps it, and engines read it back.
            # ml1143: storing nothing made D3DX12's residency manager (UE's D3D12
            # RHI) see a new queue on every submission. Names are accepted.
            if name == "SetName":
                L.append("    return S_OK;")
                L.append("}")
                continue
            if name == "GetPrivateData":
                L.append("    return mad_pd_get(This, guid, data_size, data);")
                L.append("}")
                continue
            if name == "SetPrivateData":
                L.append("    return mad_pd_set(This, guid, data_size, data);")
                L.append("}")
                continue
            if name == "SetPrivateDataInterface":
                L.append("    return mad_pd_set_iface(This, guid, data);")
                L.append("}")
                continue
            L.append('    madeira_d3d12_note_unimplemented("%s", "%s");' % (iface, name))
            if ret == "void":
                pass
            elif ret == "HRESULT":
                L.append("    return E_NOTIMPL;")
            elif "__ret" in args:
                # A struct returned by value travels through a hidden pointer on
                # this ABI, and the callee must hand that same pointer back in
                # rax. Returning NULL here crashed the engine's first GetDesc.
                L.append("    memset(__ret, 0, sizeof *__ret); return __ret;")
            else:
                z = ZERO_RETURNS.get(ret)
                if z == "zero":
                    L.append("    %s zero; memset(&zero, 0, sizeof zero); return zero;" % ret)
                elif z is not None:
                    L.append("    return %s;" % z)
                else:
                    L.append("    %s zero; memset(&zero, 0, sizeof zero); return zero;" % ret)
            L.append("}")
        L.append("")
        L.append("static void madeira_fill_%s(%sVtbl *v) {" % (iface, iface))
        for _, name, _ in methods:
            L.append("    v->%s = stub_%s_%s;" % (name, iface, name))
        L.append("}")
        L.append("")

    L.append("#endif /* MADEIRA_D3D12_STUBS_H */")
    open(out_path, "w").write("\n".join(L) + "\n")
    print("wrote %s" % out_path)
    for iface in INTERFACES:
        print("  %-28s %d slots" % (iface, len(parse(text, iface))))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    emit(sys.argv[1], sys.argv[2])
