/* GENERATED by src/pe/gen_vtables.py from d3d12.h -- do not edit by hand.
 *
 * Every vtable slot is filled with a typed stub, so an unimplemented method
 * returns E_NOTIMPL and names itself instead of jumping through a NULL slot.
 * Implemented methods are assigned over these at construction. */
#ifndef MADEIRA_D3D12_STUBS_H
#define MADEIRA_D3D12_STUBS_H

#include <d3d12.h>

/* Names every refusal once, so a game probing an unsupported method leaves a
 * trail instead of silently taking a fallback path. */
void madeira_d3d12_note_unimplemented(const char *iface, const char *method);

/* ml1143: private data is really stored, per object and GUID (madeira_d3d12.c). */
static HRESULT mad_pd_get(const void *obj, REFGUID guid, UINT *data_size, void *data);
static HRESULT mad_pd_set(const void *obj, REFGUID guid, UINT data_size, const void *data);
static HRESULT mad_pd_set_iface(const void *obj, REFGUID guid, const IUnknown *data);

/* ---- ID3D12Device10: 79 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_QueryInterface(ID3D12Device10 *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12Device10_AddRef(ID3D12Device10 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12Device10_Release(ID3D12Device10 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_GetPrivateData(ID3D12Device10 *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_SetPrivateData(ID3D12Device10 *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_SetPrivateDataInterface(ID3D12Device10 *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_SetName(ID3D12Device10 *This, const WCHAR *name) {
    return S_OK;
}
static UINT STDMETHODCALLTYPE stub_ID3D12Device10_GetNodeCount(ID3D12Device10 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetNodeCount");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommandQueue(ID3D12Device10 *This, const D3D12_COMMAND_QUEUE_DESC *desc, REFIID riid, void **command_queue) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommandQueue");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommandAllocator(ID3D12Device10 *This, D3D12_COMMAND_LIST_TYPE type, REFIID riid, void **command_allocator) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommandAllocator");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateGraphicsPipelineState(ID3D12Device10 *This, const D3D12_GRAPHICS_PIPELINE_STATE_DESC *desc, REFIID riid, void **pipeline_state) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateGraphicsPipelineState");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateComputePipelineState(ID3D12Device10 *This, const D3D12_COMPUTE_PIPELINE_STATE_DESC *desc, REFIID riid, void **pipeline_state) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateComputePipelineState");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommandList(ID3D12Device10 *This, UINT node_mask, D3D12_COMMAND_LIST_TYPE type, ID3D12CommandAllocator *command_allocator, ID3D12PipelineState *initial_pipeline_state, REFIID riid, void **command_list) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommandList");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CheckFeatureSupport(ID3D12Device10 *This, D3D12_FEATURE feature, void *feature_data, UINT feature_data_size) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CheckFeatureSupport");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateDescriptorHeap(ID3D12Device10 *This, const D3D12_DESCRIPTOR_HEAP_DESC *desc, REFIID riid, void **descriptor_heap) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateDescriptorHeap");
    return E_NOTIMPL;
}
static UINT STDMETHODCALLTYPE stub_ID3D12Device10_GetDescriptorHandleIncrementSize(ID3D12Device10 *This, D3D12_DESCRIPTOR_HEAP_TYPE descriptor_heap_type) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetDescriptorHandleIncrementSize");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateRootSignature(ID3D12Device10 *This, UINT node_mask, const void *bytecode, SIZE_T bytecode_length, REFIID riid, void **root_signature) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateRootSignature");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CreateConstantBufferView(ID3D12Device10 *This, const D3D12_CONSTANT_BUFFER_VIEW_DESC *desc, D3D12_CPU_DESCRIPTOR_HANDLE descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateConstantBufferView");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CreateShaderResourceView(ID3D12Device10 *This, ID3D12Resource *resource, const D3D12_SHADER_RESOURCE_VIEW_DESC *desc, D3D12_CPU_DESCRIPTOR_HANDLE descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateShaderResourceView");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CreateUnorderedAccessView(ID3D12Device10 *This, ID3D12Resource *resource, ID3D12Resource *counter_resource, const D3D12_UNORDERED_ACCESS_VIEW_DESC *desc, D3D12_CPU_DESCRIPTOR_HANDLE descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateUnorderedAccessView");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CreateRenderTargetView(ID3D12Device10 *This, ID3D12Resource *resource, const D3D12_RENDER_TARGET_VIEW_DESC *desc, D3D12_CPU_DESCRIPTOR_HANDLE descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateRenderTargetView");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CreateDepthStencilView(ID3D12Device10 *This, ID3D12Resource *resource, const D3D12_DEPTH_STENCIL_VIEW_DESC *desc, D3D12_CPU_DESCRIPTOR_HANDLE descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateDepthStencilView");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CreateSampler(ID3D12Device10 *This, const D3D12_SAMPLER_DESC *desc, D3D12_CPU_DESCRIPTOR_HANDLE descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateSampler");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CopyDescriptors(ID3D12Device10 *This, UINT dst_descriptor_range_count, const D3D12_CPU_DESCRIPTOR_HANDLE *dst_descriptor_range_offsets, const UINT *dst_descriptor_range_sizes, UINT src_descriptor_range_count, const D3D12_CPU_DESCRIPTOR_HANDLE *src_descriptor_range_offsets, const UINT *src_descriptor_range_sizes, D3D12_DESCRIPTOR_HEAP_TYPE descriptor_heap_type) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CopyDescriptors");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CopyDescriptorsSimple(ID3D12Device10 *This, UINT descriptor_count, const D3D12_CPU_DESCRIPTOR_HANDLE dst_descriptor_range_offset, const D3D12_CPU_DESCRIPTOR_HANDLE src_descriptor_range_offset, D3D12_DESCRIPTOR_HEAP_TYPE descriptor_heap_type) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CopyDescriptorsSimple");
}
static D3D12_RESOURCE_ALLOCATION_INFO * STDMETHODCALLTYPE stub_ID3D12Device10_GetResourceAllocationInfo(ID3D12Device10 *This, D3D12_RESOURCE_ALLOCATION_INFO *__ret, UINT visible_mask, UINT reource_desc_count, const D3D12_RESOURCE_DESC *resource_descs) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetResourceAllocationInfo");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static D3D12_HEAP_PROPERTIES * STDMETHODCALLTYPE stub_ID3D12Device10_GetCustomHeapProperties(ID3D12Device10 *This, D3D12_HEAP_PROPERTIES *__ret, UINT node_mask, D3D12_HEAP_TYPE heap_type) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetCustomHeapProperties");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommittedResource(ID3D12Device10 *This, const D3D12_HEAP_PROPERTIES *heap_properties, D3D12_HEAP_FLAGS heap_flags, const D3D12_RESOURCE_DESC *desc, D3D12_RESOURCE_STATES initial_state, const D3D12_CLEAR_VALUE *optimized_clear_value, REFIID riid, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommittedResource");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateHeap(ID3D12Device10 *This, const D3D12_HEAP_DESC *desc, REFIID riid, void **heap) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateHeap");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreatePlacedResource(ID3D12Device10 *This, ID3D12Heap *heap, UINT64 heap_offset, const D3D12_RESOURCE_DESC *desc, D3D12_RESOURCE_STATES initial_state, const D3D12_CLEAR_VALUE *optimized_clear_value, REFIID riid, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreatePlacedResource");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateReservedResource(ID3D12Device10 *This, const D3D12_RESOURCE_DESC *desc, D3D12_RESOURCE_STATES initial_state, const D3D12_CLEAR_VALUE *optimized_clear_value, REFIID riid, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateReservedResource");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateSharedHandle(ID3D12Device10 *This, ID3D12DeviceChild *object, const SECURITY_ATTRIBUTES *attributes, DWORD access, const WCHAR *name, HANDLE *handle) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateSharedHandle");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_OpenSharedHandle(ID3D12Device10 *This, HANDLE handle, REFIID riid, void **object) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "OpenSharedHandle");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_OpenSharedHandleByName(ID3D12Device10 *This, const WCHAR *name, DWORD access, HANDLE *handle) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "OpenSharedHandleByName");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_MakeResident(ID3D12Device10 *This, UINT object_count, ID3D12Pageable *const *objects) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "MakeResident");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_Evict(ID3D12Device10 *This, UINT object_count, ID3D12Pageable *const *objects) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "Evict");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateFence(ID3D12Device10 *This, UINT64 initial_value, D3D12_FENCE_FLAGS flags, REFIID riid, void **fence) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateFence");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_GetDeviceRemovedReason(ID3D12Device10 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetDeviceRemovedReason");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_GetCopyableFootprints(ID3D12Device10 *This, const D3D12_RESOURCE_DESC *desc, UINT first_sub_resource, UINT sub_resource_count, UINT64 base_offset, D3D12_PLACED_SUBRESOURCE_FOOTPRINT *layouts, UINT *row_count, UINT64 *row_size, UINT64 *total_bytes) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetCopyableFootprints");
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateQueryHeap(ID3D12Device10 *This, const D3D12_QUERY_HEAP_DESC *desc, REFIID riid, void **heap) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateQueryHeap");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_SetStablePowerState(ID3D12Device10 *This, WINBOOL enable) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "SetStablePowerState");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommandSignature(ID3D12Device10 *This, const D3D12_COMMAND_SIGNATURE_DESC *desc, ID3D12RootSignature *root_signature, REFIID riid, void **command_signature) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommandSignature");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_GetResourceTiling(ID3D12Device10 *This, ID3D12Resource *resource, UINT *total_tile_count, D3D12_PACKED_MIP_INFO *packed_mip_info, D3D12_TILE_SHAPE *standard_tile_shape, UINT *sub_resource_tiling_count, UINT first_sub_resource_tiling, D3D12_SUBRESOURCE_TILING *sub_resource_tilings) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetResourceTiling");
}
static LUID * STDMETHODCALLTYPE stub_ID3D12Device10_GetAdapterLuid(ID3D12Device10 *This, LUID *__ret) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetAdapterLuid");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreatePipelineLibrary(ID3D12Device10 *This, const void *blob, SIZE_T blob_size, REFIID iid, void **lib) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreatePipelineLibrary");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_SetEventOnMultipleFenceCompletion(ID3D12Device10 *This, ID3D12Fence *const *fences, const UINT64 *values, UINT fence_count, D3D12_MULTIPLE_FENCE_WAIT_FLAGS flags, HANDLE event) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "SetEventOnMultipleFenceCompletion");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_SetResidencyPriority(ID3D12Device10 *This, UINT object_count, ID3D12Pageable *const *objects, const D3D12_RESIDENCY_PRIORITY *priorities) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "SetResidencyPriority");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreatePipelineState(ID3D12Device10 *This, const D3D12_PIPELINE_STATE_STREAM_DESC *desc, REFIID riid, void **pipeline_state) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreatePipelineState");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_OpenExistingHeapFromAddress(ID3D12Device10 *This, const void *address, REFIID riid, void **heap) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "OpenExistingHeapFromAddress");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_OpenExistingHeapFromFileMapping(ID3D12Device10 *This, HANDLE file_mapping, REFIID riid, void **heap) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "OpenExistingHeapFromFileMapping");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_EnqueueMakeResident(ID3D12Device10 *This, D3D12_RESIDENCY_FLAGS flags, UINT num_objects, ID3D12Pageable *const *objects, ID3D12Fence *fence, UINT64 fence_value) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "EnqueueMakeResident");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommandList1(ID3D12Device10 *This, UINT node_mask, D3D12_COMMAND_LIST_TYPE type, D3D12_COMMAND_LIST_FLAGS flags, REFIID riid, void **command_list) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommandList1");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateProtectedResourceSession(ID3D12Device10 *This, const D3D12_PROTECTED_RESOURCE_SESSION_DESC *desc, REFIID riid, void **session) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateProtectedResourceSession");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommittedResource1(ID3D12Device10 *This, const D3D12_HEAP_PROPERTIES *heap_properties, D3D12_HEAP_FLAGS heap_flags, const D3D12_RESOURCE_DESC *desc, D3D12_RESOURCE_STATES initial_resource_state, const D3D12_CLEAR_VALUE *optimized_clear_value, ID3D12ProtectedResourceSession *protected_session, REFIID riid_resource, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommittedResource1");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateHeap1(ID3D12Device10 *This, const D3D12_HEAP_DESC *desc, ID3D12ProtectedResourceSession *protected_session, REFIID riid, void **heap) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateHeap1");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateReservedResource1(ID3D12Device10 *This, const D3D12_RESOURCE_DESC *desc, D3D12_RESOURCE_STATES initial_state, const D3D12_CLEAR_VALUE *optimized_clear_value, ID3D12ProtectedResourceSession *protected_session, REFIID riid, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateReservedResource1");
    return E_NOTIMPL;
}
static D3D12_RESOURCE_ALLOCATION_INFO * STDMETHODCALLTYPE stub_ID3D12Device10_GetResourceAllocationInfo1(ID3D12Device10 *This, D3D12_RESOURCE_ALLOCATION_INFO *__ret, UINT visible_mask, UINT resource_descs_count, const D3D12_RESOURCE_DESC *resource_descs, D3D12_RESOURCE_ALLOCATION_INFO1 *resource_allocation_info1) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetResourceAllocationInfo1");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateLifetimeTracker(ID3D12Device10 *This, ID3D12LifetimeOwner *owner, REFIID riid, void **tracker) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateLifetimeTracker");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_RemoveDevice(ID3D12Device10 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "RemoveDevice");
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_EnumerateMetaCommands(ID3D12Device10 *This, UINT *meta_commands_count, D3D12_META_COMMAND_DESC *descs) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "EnumerateMetaCommands");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_EnumerateMetaCommandParameters(ID3D12Device10 *This, REFGUID command_id, D3D12_META_COMMAND_PARAMETER_STAGE stage, UINT *total_structure_size_in_bytes, UINT *parameter_count, D3D12_META_COMMAND_PARAMETER_DESC *parameter_descs) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "EnumerateMetaCommandParameters");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateMetaCommand(ID3D12Device10 *This, REFGUID command_id, UINT node_mask, const void *creation_parameters_data, SIZE_T creation_parameters_data_size_in_bytes, REFIID riid, void **meta_command) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateMetaCommand");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateStateObject(ID3D12Device10 *This, const D3D12_STATE_OBJECT_DESC *desc, REFIID riid, void **state_object) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateStateObject");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_GetRaytracingAccelerationStructurePrebuildInfo(ID3D12Device10 *This, const D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS *desc, D3D12_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO *info) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetRaytracingAccelerationStructurePrebuildInfo");
}
static D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS STDMETHODCALLTYPE stub_ID3D12Device10_CheckDriverMatchingIdentifier(ID3D12Device10 *This, D3D12_SERIALIZED_DATA_TYPE serialized_data_type, const D3D12_SERIALIZED_DATA_DRIVER_MATCHING_IDENTIFIER *identifier_to_check) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CheckDriverMatchingIdentifier");
    D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS zero; memset(&zero, 0, sizeof zero); return zero;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_SetBackgroundProcessingMode(ID3D12Device10 *This, D3D12_BACKGROUND_PROCESSING_MODE mode, D3D12_MEASUREMENTS_ACTION action, HANDLE event, WINBOOL *further_measurements_desired) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "SetBackgroundProcessingMode");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_AddToStateObject(ID3D12Device10 *This, const D3D12_STATE_OBJECT_DESC *addition, ID3D12StateObject *state_object_to_grow_from, REFIID riid, void **new_state_object) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "AddToStateObject");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateProtectedResourceSession1(ID3D12Device10 *This, const D3D12_PROTECTED_RESOURCE_SESSION_DESC1 *desc, REFIID riid, void **session) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateProtectedResourceSession1");
    return E_NOTIMPL;
}
static D3D12_RESOURCE_ALLOCATION_INFO * STDMETHODCALLTYPE stub_ID3D12Device10_GetResourceAllocationInfo2(ID3D12Device10 *This, D3D12_RESOURCE_ALLOCATION_INFO *__ret, UINT visible_mask, UINT resource_descs_count, const D3D12_RESOURCE_DESC1 *resource_descs, D3D12_RESOURCE_ALLOCATION_INFO1 *resource_allocation_info1) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetResourceAllocationInfo2");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommittedResource2(ID3D12Device10 *This, const D3D12_HEAP_PROPERTIES *heap_properties, D3D12_HEAP_FLAGS heap_flags, const D3D12_RESOURCE_DESC1 *desc, D3D12_RESOURCE_STATES initial_resource_state, const D3D12_CLEAR_VALUE *optimized_clear_value, ID3D12ProtectedResourceSession *protected_session, REFIID riid_resource, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommittedResource2");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreatePlacedResource1(ID3D12Device10 *This, ID3D12Heap *heap, UINT64 heap_offset, const D3D12_RESOURCE_DESC1 *desc, D3D12_RESOURCE_STATES initial_state, const D3D12_CLEAR_VALUE *optimized_clear_value, REFIID riid, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreatePlacedResource1");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_CreateSamplerFeedbackUnorderedAccessView(ID3D12Device10 *This, ID3D12Resource *targeted_resource, ID3D12Resource *feedback_resource, D3D12_CPU_DESCRIPTOR_HANDLE dst_descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateSamplerFeedbackUnorderedAccessView");
}
static void STDMETHODCALLTYPE stub_ID3D12Device10_GetCopyableFootprints1(ID3D12Device10 *This, const D3D12_RESOURCE_DESC1 *resource_desc, UINT first_subresource, UINT subresources_count, UINT64 base_offset, D3D12_PLACED_SUBRESOURCE_FOOTPRINT *layouts, UINT *rows_count, UINT64 *row_size_in_bytes, UINT64 *total_bytes) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "GetCopyableFootprints1");
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateShaderCacheSession(ID3D12Device10 *This, const D3D12_SHADER_CACHE_SESSION_DESC *desc, REFIID riid, void **session) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateShaderCacheSession");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_ShaderCacheControl(ID3D12Device10 *This, D3D12_SHADER_CACHE_KIND_FLAGS kinds, D3D12_SHADER_CACHE_CONTROL_FLAGS control) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "ShaderCacheControl");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommandQueue1(ID3D12Device10 *This, const D3D12_COMMAND_QUEUE_DESC *desc, REFIID creator_id, REFIID riid, void **command_queue) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommandQueue1");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateCommittedResource3(ID3D12Device10 *This, const D3D12_HEAP_PROPERTIES *heap_properties, D3D12_HEAP_FLAGS heap_flags, const D3D12_RESOURCE_DESC1 *desc, D3D12_BARRIER_LAYOUT initial_layout, const D3D12_CLEAR_VALUE *optimized_clear_value, ID3D12ProtectedResourceSession *protected_session, UINT32 castable_formats_count, DXGI_FORMAT *castable_formats, REFIID riid_resource, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateCommittedResource3");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreatePlacedResource2(ID3D12Device10 *This, ID3D12Heap *heap, UINT64 heap_offset, const D3D12_RESOURCE_DESC1 *desc, D3D12_BARRIER_LAYOUT initial_layout, const D3D12_CLEAR_VALUE *optimized_clear_value, UINT32 castable_formats_count, DXGI_FORMAT *castable_formats, REFIID riid, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreatePlacedResource2");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Device10_CreateReservedResource2(ID3D12Device10 *This, const D3D12_RESOURCE_DESC *desc, D3D12_BARRIER_LAYOUT initial_layout, const D3D12_CLEAR_VALUE *optimized_clear_value, ID3D12ProtectedResourceSession *protected_session, UINT32 castable_formats_count, DXGI_FORMAT *castable_formats, REFIID riid, void **resource) {
    madeira_d3d12_note_unimplemented("ID3D12Device10", "CreateReservedResource2");
    return E_NOTIMPL;
}

static void madeira_fill_ID3D12Device10(ID3D12Device10Vtbl *v) {
    v->QueryInterface = stub_ID3D12Device10_QueryInterface;
    v->AddRef = stub_ID3D12Device10_AddRef;
    v->Release = stub_ID3D12Device10_Release;
    v->GetPrivateData = stub_ID3D12Device10_GetPrivateData;
    v->SetPrivateData = stub_ID3D12Device10_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12Device10_SetPrivateDataInterface;
    v->SetName = stub_ID3D12Device10_SetName;
    v->GetNodeCount = stub_ID3D12Device10_GetNodeCount;
    v->CreateCommandQueue = stub_ID3D12Device10_CreateCommandQueue;
    v->CreateCommandAllocator = stub_ID3D12Device10_CreateCommandAllocator;
    v->CreateGraphicsPipelineState = stub_ID3D12Device10_CreateGraphicsPipelineState;
    v->CreateComputePipelineState = stub_ID3D12Device10_CreateComputePipelineState;
    v->CreateCommandList = stub_ID3D12Device10_CreateCommandList;
    v->CheckFeatureSupport = stub_ID3D12Device10_CheckFeatureSupport;
    v->CreateDescriptorHeap = stub_ID3D12Device10_CreateDescriptorHeap;
    v->GetDescriptorHandleIncrementSize = stub_ID3D12Device10_GetDescriptorHandleIncrementSize;
    v->CreateRootSignature = stub_ID3D12Device10_CreateRootSignature;
    v->CreateConstantBufferView = stub_ID3D12Device10_CreateConstantBufferView;
    v->CreateShaderResourceView = stub_ID3D12Device10_CreateShaderResourceView;
    v->CreateUnorderedAccessView = stub_ID3D12Device10_CreateUnorderedAccessView;
    v->CreateRenderTargetView = stub_ID3D12Device10_CreateRenderTargetView;
    v->CreateDepthStencilView = stub_ID3D12Device10_CreateDepthStencilView;
    v->CreateSampler = stub_ID3D12Device10_CreateSampler;
    v->CopyDescriptors = stub_ID3D12Device10_CopyDescriptors;
    v->CopyDescriptorsSimple = stub_ID3D12Device10_CopyDescriptorsSimple;
    v->GetResourceAllocationInfo = stub_ID3D12Device10_GetResourceAllocationInfo;
    v->GetCustomHeapProperties = stub_ID3D12Device10_GetCustomHeapProperties;
    v->CreateCommittedResource = stub_ID3D12Device10_CreateCommittedResource;
    v->CreateHeap = stub_ID3D12Device10_CreateHeap;
    v->CreatePlacedResource = stub_ID3D12Device10_CreatePlacedResource;
    v->CreateReservedResource = stub_ID3D12Device10_CreateReservedResource;
    v->CreateSharedHandle = stub_ID3D12Device10_CreateSharedHandle;
    v->OpenSharedHandle = stub_ID3D12Device10_OpenSharedHandle;
    v->OpenSharedHandleByName = stub_ID3D12Device10_OpenSharedHandleByName;
    v->MakeResident = stub_ID3D12Device10_MakeResident;
    v->Evict = stub_ID3D12Device10_Evict;
    v->CreateFence = stub_ID3D12Device10_CreateFence;
    v->GetDeviceRemovedReason = stub_ID3D12Device10_GetDeviceRemovedReason;
    v->GetCopyableFootprints = stub_ID3D12Device10_GetCopyableFootprints;
    v->CreateQueryHeap = stub_ID3D12Device10_CreateQueryHeap;
    v->SetStablePowerState = stub_ID3D12Device10_SetStablePowerState;
    v->CreateCommandSignature = stub_ID3D12Device10_CreateCommandSignature;
    v->GetResourceTiling = stub_ID3D12Device10_GetResourceTiling;
    v->GetAdapterLuid = stub_ID3D12Device10_GetAdapterLuid;
    v->CreatePipelineLibrary = stub_ID3D12Device10_CreatePipelineLibrary;
    v->SetEventOnMultipleFenceCompletion = stub_ID3D12Device10_SetEventOnMultipleFenceCompletion;
    v->SetResidencyPriority = stub_ID3D12Device10_SetResidencyPriority;
    v->CreatePipelineState = stub_ID3D12Device10_CreatePipelineState;
    v->OpenExistingHeapFromAddress = stub_ID3D12Device10_OpenExistingHeapFromAddress;
    v->OpenExistingHeapFromFileMapping = stub_ID3D12Device10_OpenExistingHeapFromFileMapping;
    v->EnqueueMakeResident = stub_ID3D12Device10_EnqueueMakeResident;
    v->CreateCommandList1 = stub_ID3D12Device10_CreateCommandList1;
    v->CreateProtectedResourceSession = stub_ID3D12Device10_CreateProtectedResourceSession;
    v->CreateCommittedResource1 = stub_ID3D12Device10_CreateCommittedResource1;
    v->CreateHeap1 = stub_ID3D12Device10_CreateHeap1;
    v->CreateReservedResource1 = stub_ID3D12Device10_CreateReservedResource1;
    v->GetResourceAllocationInfo1 = stub_ID3D12Device10_GetResourceAllocationInfo1;
    v->CreateLifetimeTracker = stub_ID3D12Device10_CreateLifetimeTracker;
    v->RemoveDevice = stub_ID3D12Device10_RemoveDevice;
    v->EnumerateMetaCommands = stub_ID3D12Device10_EnumerateMetaCommands;
    v->EnumerateMetaCommandParameters = stub_ID3D12Device10_EnumerateMetaCommandParameters;
    v->CreateMetaCommand = stub_ID3D12Device10_CreateMetaCommand;
    v->CreateStateObject = stub_ID3D12Device10_CreateStateObject;
    v->GetRaytracingAccelerationStructurePrebuildInfo = stub_ID3D12Device10_GetRaytracingAccelerationStructurePrebuildInfo;
    v->CheckDriverMatchingIdentifier = stub_ID3D12Device10_CheckDriverMatchingIdentifier;
    v->SetBackgroundProcessingMode = stub_ID3D12Device10_SetBackgroundProcessingMode;
    v->AddToStateObject = stub_ID3D12Device10_AddToStateObject;
    v->CreateProtectedResourceSession1 = stub_ID3D12Device10_CreateProtectedResourceSession1;
    v->GetResourceAllocationInfo2 = stub_ID3D12Device10_GetResourceAllocationInfo2;
    v->CreateCommittedResource2 = stub_ID3D12Device10_CreateCommittedResource2;
    v->CreatePlacedResource1 = stub_ID3D12Device10_CreatePlacedResource1;
    v->CreateSamplerFeedbackUnorderedAccessView = stub_ID3D12Device10_CreateSamplerFeedbackUnorderedAccessView;
    v->GetCopyableFootprints1 = stub_ID3D12Device10_GetCopyableFootprints1;
    v->CreateShaderCacheSession = stub_ID3D12Device10_CreateShaderCacheSession;
    v->ShaderCacheControl = stub_ID3D12Device10_ShaderCacheControl;
    v->CreateCommandQueue1 = stub_ID3D12Device10_CreateCommandQueue1;
    v->CreateCommittedResource3 = stub_ID3D12Device10_CreateCommittedResource3;
    v->CreatePlacedResource2 = stub_ID3D12Device10_CreatePlacedResource2;
    v->CreateReservedResource2 = stub_ID3D12Device10_CreateReservedResource2;
}

/* ---- ID3D12CommandQueue: 19 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_QueryInterface(ID3D12CommandQueue *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12CommandQueue_AddRef(ID3D12CommandQueue *This) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12CommandQueue_Release(ID3D12CommandQueue *This) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_GetPrivateData(ID3D12CommandQueue *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_SetPrivateData(ID3D12CommandQueue *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_SetPrivateDataInterface(ID3D12CommandQueue *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_SetName(ID3D12CommandQueue *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_GetDevice(ID3D12CommandQueue *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "GetDevice");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12CommandQueue_UpdateTileMappings(ID3D12CommandQueue *This, ID3D12Resource *resource, UINT region_count, const D3D12_TILED_RESOURCE_COORDINATE *region_start_coordinates, const D3D12_TILE_REGION_SIZE *region_sizes, ID3D12Heap *heap, UINT range_count, const D3D12_TILE_RANGE_FLAGS *range_flags, const UINT *heap_range_offsets, const UINT *range_tile_counts, D3D12_TILE_MAPPING_FLAGS flags) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "UpdateTileMappings");
}
static void STDMETHODCALLTYPE stub_ID3D12CommandQueue_CopyTileMappings(ID3D12CommandQueue *This, ID3D12Resource *dst_resource, const D3D12_TILED_RESOURCE_COORDINATE *dst_region_start_coordinate, ID3D12Resource *src_resource, const D3D12_TILED_RESOURCE_COORDINATE *src_region_start_coordinate, const D3D12_TILE_REGION_SIZE *region_size, D3D12_TILE_MAPPING_FLAGS flags) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "CopyTileMappings");
}
static void STDMETHODCALLTYPE stub_ID3D12CommandQueue_ExecuteCommandLists(ID3D12CommandQueue *This, UINT command_list_count, ID3D12CommandList *const *command_lists) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "ExecuteCommandLists");
}
static void STDMETHODCALLTYPE stub_ID3D12CommandQueue_SetMarker(ID3D12CommandQueue *This, UINT metadata, const void *data, UINT size) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "SetMarker");
}
static void STDMETHODCALLTYPE stub_ID3D12CommandQueue_BeginEvent(ID3D12CommandQueue *This, UINT metadata, const void *data, UINT size) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "BeginEvent");
}
static void STDMETHODCALLTYPE stub_ID3D12CommandQueue_EndEvent(ID3D12CommandQueue *This) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "EndEvent");
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_Signal(ID3D12CommandQueue *This, ID3D12Fence *fence, UINT64 value) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "Signal");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_Wait(ID3D12CommandQueue *This, ID3D12Fence *fence, UINT64 value) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "Wait");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_GetTimestampFrequency(ID3D12CommandQueue *This, UINT64 *frequency) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "GetTimestampFrequency");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandQueue_GetClockCalibration(ID3D12CommandQueue *This, UINT64 *gpu_timestamp, UINT64 *cpu_timestamp) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "GetClockCalibration");
    return E_NOTIMPL;
}
static D3D12_COMMAND_QUEUE_DESC * STDMETHODCALLTYPE stub_ID3D12CommandQueue_GetDesc(ID3D12CommandQueue *This, D3D12_COMMAND_QUEUE_DESC *__ret) {
    madeira_d3d12_note_unimplemented("ID3D12CommandQueue", "GetDesc");
    memset(__ret, 0, sizeof *__ret); return __ret;
}

static void madeira_fill_ID3D12CommandQueue(ID3D12CommandQueueVtbl *v) {
    v->QueryInterface = stub_ID3D12CommandQueue_QueryInterface;
    v->AddRef = stub_ID3D12CommandQueue_AddRef;
    v->Release = stub_ID3D12CommandQueue_Release;
    v->GetPrivateData = stub_ID3D12CommandQueue_GetPrivateData;
    v->SetPrivateData = stub_ID3D12CommandQueue_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12CommandQueue_SetPrivateDataInterface;
    v->SetName = stub_ID3D12CommandQueue_SetName;
    v->GetDevice = stub_ID3D12CommandQueue_GetDevice;
    v->UpdateTileMappings = stub_ID3D12CommandQueue_UpdateTileMappings;
    v->CopyTileMappings = stub_ID3D12CommandQueue_CopyTileMappings;
    v->ExecuteCommandLists = stub_ID3D12CommandQueue_ExecuteCommandLists;
    v->SetMarker = stub_ID3D12CommandQueue_SetMarker;
    v->BeginEvent = stub_ID3D12CommandQueue_BeginEvent;
    v->EndEvent = stub_ID3D12CommandQueue_EndEvent;
    v->Signal = stub_ID3D12CommandQueue_Signal;
    v->Wait = stub_ID3D12CommandQueue_Wait;
    v->GetTimestampFrequency = stub_ID3D12CommandQueue_GetTimestampFrequency;
    v->GetClockCalibration = stub_ID3D12CommandQueue_GetClockCalibration;
    v->GetDesc = stub_ID3D12CommandQueue_GetDesc;
}

/* ---- ID3D12CommandAllocator: 9 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandAllocator_QueryInterface(ID3D12CommandAllocator *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12CommandAllocator", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12CommandAllocator_AddRef(ID3D12CommandAllocator *This) {
    madeira_d3d12_note_unimplemented("ID3D12CommandAllocator", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12CommandAllocator_Release(ID3D12CommandAllocator *This) {
    madeira_d3d12_note_unimplemented("ID3D12CommandAllocator", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandAllocator_GetPrivateData(ID3D12CommandAllocator *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandAllocator_SetPrivateData(ID3D12CommandAllocator *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandAllocator_SetPrivateDataInterface(ID3D12CommandAllocator *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandAllocator_SetName(ID3D12CommandAllocator *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandAllocator_GetDevice(ID3D12CommandAllocator *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12CommandAllocator", "GetDevice");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12CommandAllocator_Reset(ID3D12CommandAllocator *This) {
    madeira_d3d12_note_unimplemented("ID3D12CommandAllocator", "Reset");
    return E_NOTIMPL;
}

static void madeira_fill_ID3D12CommandAllocator(ID3D12CommandAllocatorVtbl *v) {
    v->QueryInterface = stub_ID3D12CommandAllocator_QueryInterface;
    v->AddRef = stub_ID3D12CommandAllocator_AddRef;
    v->Release = stub_ID3D12CommandAllocator_Release;
    v->GetPrivateData = stub_ID3D12CommandAllocator_GetPrivateData;
    v->SetPrivateData = stub_ID3D12CommandAllocator_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12CommandAllocator_SetPrivateDataInterface;
    v->SetName = stub_ID3D12CommandAllocator_SetName;
    v->GetDevice = stub_ID3D12CommandAllocator_GetDevice;
    v->Reset = stub_ID3D12CommandAllocator_Reset;
}

/* ---- ID3D12GraphicsCommandList7: 81 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_QueryInterface(ID3D12GraphicsCommandList7 *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_AddRef(ID3D12GraphicsCommandList7 *This) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_Release(ID3D12GraphicsCommandList7 *This) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_GetPrivateData(ID3D12GraphicsCommandList7 *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetPrivateData(ID3D12GraphicsCommandList7 *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetPrivateDataInterface(ID3D12GraphicsCommandList7 *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetName(ID3D12GraphicsCommandList7 *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_GetDevice(ID3D12GraphicsCommandList7 *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "GetDevice");
    return E_NOTIMPL;
}
static D3D12_COMMAND_LIST_TYPE STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_GetType(ID3D12GraphicsCommandList7 *This) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "GetType");
    return (D3D12_COMMAND_LIST_TYPE)0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_Close(ID3D12GraphicsCommandList7 *This) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "Close");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_Reset(ID3D12GraphicsCommandList7 *This, ID3D12CommandAllocator *allocator, ID3D12PipelineState *initial_state) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "Reset");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ClearState(ID3D12GraphicsCommandList7 *This, ID3D12PipelineState *pipeline_state) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ClearState");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_DrawInstanced(ID3D12GraphicsCommandList7 *This, UINT vertex_count_per_instance, UINT instance_count, UINT start_vertex_location, UINT start_instance_location) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "DrawInstanced");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_DrawIndexedInstanced(ID3D12GraphicsCommandList7 *This, UINT index_count_per_instance, UINT instance_count, UINT start_vertex_location, INT base_vertex_location, UINT start_instance_location) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "DrawIndexedInstanced");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_Dispatch(ID3D12GraphicsCommandList7 *This, UINT x, UINT u, UINT z) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "Dispatch");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_CopyBufferRegion(ID3D12GraphicsCommandList7 *This, ID3D12Resource *dst_buffer, UINT64 dst_offset, ID3D12Resource *src_buffer, UINT64 src_offset, UINT64 byte_count) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "CopyBufferRegion");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_CopyTextureRegion(ID3D12GraphicsCommandList7 *This, const D3D12_TEXTURE_COPY_LOCATION *dst, UINT dst_x, UINT dst_y, UINT dst_z, const D3D12_TEXTURE_COPY_LOCATION *src, const D3D12_BOX *src_box) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "CopyTextureRegion");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_CopyResource(ID3D12GraphicsCommandList7 *This, ID3D12Resource *dst_resource, ID3D12Resource *src_resource) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "CopyResource");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_CopyTiles(ID3D12GraphicsCommandList7 *This, ID3D12Resource *tiled_resource, const D3D12_TILED_RESOURCE_COORDINATE *tile_region_start_coordinate, const D3D12_TILE_REGION_SIZE *tile_region_size, ID3D12Resource *buffer, UINT64 buffer_offset, D3D12_TILE_COPY_FLAGS flags) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "CopyTiles");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ResolveSubresource(ID3D12GraphicsCommandList7 *This, ID3D12Resource *dst_resource, UINT dst_sub_resource, ID3D12Resource *src_resource, UINT src_sub_resource, DXGI_FORMAT format) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ResolveSubresource");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_IASetPrimitiveTopology(ID3D12GraphicsCommandList7 *This, D3D12_PRIMITIVE_TOPOLOGY primitive_topology) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "IASetPrimitiveTopology");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_RSSetViewports(ID3D12GraphicsCommandList7 *This, UINT viewport_count, const D3D12_VIEWPORT *viewports) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "RSSetViewports");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_RSSetScissorRects(ID3D12GraphicsCommandList7 *This, UINT rect_count, const D3D12_RECT *rects) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "RSSetScissorRects");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_OMSetBlendFactor(ID3D12GraphicsCommandList7 *This, const FLOAT blend_factor[4]) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "OMSetBlendFactor");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_OMSetStencilRef(ID3D12GraphicsCommandList7 *This, UINT stencil_ref) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "OMSetStencilRef");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetPipelineState(ID3D12GraphicsCommandList7 *This, ID3D12PipelineState *pipeline_state) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetPipelineState");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ResourceBarrier(ID3D12GraphicsCommandList7 *This, UINT barrier_count, const D3D12_RESOURCE_BARRIER *barriers) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ResourceBarrier");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ExecuteBundle(ID3D12GraphicsCommandList7 *This, ID3D12GraphicsCommandList *command_list) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ExecuteBundle");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetDescriptorHeaps(ID3D12GraphicsCommandList7 *This, UINT heap_count, ID3D12DescriptorHeap *const *heaps) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetDescriptorHeaps");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetComputeRootSignature(ID3D12GraphicsCommandList7 *This, ID3D12RootSignature *root_signature) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetComputeRootSignature");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetGraphicsRootSignature(ID3D12GraphicsCommandList7 *This, ID3D12RootSignature *root_signature) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetGraphicsRootSignature");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetComputeRootDescriptorTable(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_DESCRIPTOR_HANDLE base_descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetComputeRootDescriptorTable");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetGraphicsRootDescriptorTable(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_DESCRIPTOR_HANDLE base_descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetGraphicsRootDescriptorTable");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetComputeRoot32BitConstant(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, UINT data, UINT dst_offset) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetComputeRoot32BitConstant");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetGraphicsRoot32BitConstant(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, UINT data, UINT dst_offset) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetGraphicsRoot32BitConstant");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetComputeRoot32BitConstants(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, UINT constant_count, const void *data, UINT dst_offset) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetComputeRoot32BitConstants");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetGraphicsRoot32BitConstants(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, UINT constant_count, const void *data, UINT dst_offset) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetGraphicsRoot32BitConstants");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetComputeRootConstantBufferView(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_VIRTUAL_ADDRESS address) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetComputeRootConstantBufferView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetGraphicsRootConstantBufferView(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_VIRTUAL_ADDRESS address) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetGraphicsRootConstantBufferView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetComputeRootShaderResourceView(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_VIRTUAL_ADDRESS address) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetComputeRootShaderResourceView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetGraphicsRootShaderResourceView(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_VIRTUAL_ADDRESS address) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetGraphicsRootShaderResourceView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetComputeRootUnorderedAccessView(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_VIRTUAL_ADDRESS address) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetComputeRootUnorderedAccessView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetGraphicsRootUnorderedAccessView(ID3D12GraphicsCommandList7 *This, UINT root_parameter_index, D3D12_GPU_VIRTUAL_ADDRESS address) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetGraphicsRootUnorderedAccessView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_IASetIndexBuffer(ID3D12GraphicsCommandList7 *This, const D3D12_INDEX_BUFFER_VIEW *view) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "IASetIndexBuffer");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_IASetVertexBuffers(ID3D12GraphicsCommandList7 *This, UINT start_slot, UINT view_count, const D3D12_VERTEX_BUFFER_VIEW *views) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "IASetVertexBuffers");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SOSetTargets(ID3D12GraphicsCommandList7 *This, UINT start_slot, UINT view_count, const D3D12_STREAM_OUTPUT_BUFFER_VIEW *views) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SOSetTargets");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_OMSetRenderTargets(ID3D12GraphicsCommandList7 *This, UINT render_target_descriptor_count, const D3D12_CPU_DESCRIPTOR_HANDLE *render_target_descriptors, WINBOOL single_descriptor_handle, const D3D12_CPU_DESCRIPTOR_HANDLE *depth_stencil_descriptor) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "OMSetRenderTargets");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ClearDepthStencilView(ID3D12GraphicsCommandList7 *This, D3D12_CPU_DESCRIPTOR_HANDLE dsv, D3D12_CLEAR_FLAGS flags, FLOAT depth, UINT8 stencil, UINT rect_count, const D3D12_RECT *rects) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ClearDepthStencilView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ClearRenderTargetView(ID3D12GraphicsCommandList7 *This, D3D12_CPU_DESCRIPTOR_HANDLE rtv, const FLOAT color[4], UINT rect_count, const D3D12_RECT *rects) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ClearRenderTargetView");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ClearUnorderedAccessViewUint(ID3D12GraphicsCommandList7 *This, D3D12_GPU_DESCRIPTOR_HANDLE gpu_handle, D3D12_CPU_DESCRIPTOR_HANDLE cpu_handle, ID3D12Resource *resource, const UINT values[4], UINT rect_count, const D3D12_RECT *rects) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ClearUnorderedAccessViewUint");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ClearUnorderedAccessViewFloat(ID3D12GraphicsCommandList7 *This, D3D12_GPU_DESCRIPTOR_HANDLE gpu_handle, D3D12_CPU_DESCRIPTOR_HANDLE cpu_handle, ID3D12Resource *resource, const float values[4], UINT rect_count, const D3D12_RECT *rects) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ClearUnorderedAccessViewFloat");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_DiscardResource(ID3D12GraphicsCommandList7 *This, ID3D12Resource *resource, const D3D12_DISCARD_REGION *region) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "DiscardResource");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_BeginQuery(ID3D12GraphicsCommandList7 *This, ID3D12QueryHeap *heap, D3D12_QUERY_TYPE type, UINT index) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "BeginQuery");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_EndQuery(ID3D12GraphicsCommandList7 *This, ID3D12QueryHeap *heap, D3D12_QUERY_TYPE type, UINT index) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "EndQuery");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ResolveQueryData(ID3D12GraphicsCommandList7 *This, ID3D12QueryHeap *heap, D3D12_QUERY_TYPE type, UINT start_index, UINT query_count, ID3D12Resource *dst_buffer, UINT64 aligned_dst_buffer_offset) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ResolveQueryData");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetPredication(ID3D12GraphicsCommandList7 *This, ID3D12Resource *buffer, UINT64 aligned_buffer_offset, D3D12_PREDICATION_OP operation) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetPredication");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetMarker(ID3D12GraphicsCommandList7 *This, UINT metadata, const void *data, UINT size) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetMarker");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_BeginEvent(ID3D12GraphicsCommandList7 *This, UINT metadata, const void *data, UINT size) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "BeginEvent");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_EndEvent(ID3D12GraphicsCommandList7 *This) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "EndEvent");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ExecuteIndirect(ID3D12GraphicsCommandList7 *This, ID3D12CommandSignature *command_signature, UINT max_command_count, ID3D12Resource *arg_buffer, UINT64 arg_buffer_offset, ID3D12Resource *count_buffer, UINT64 count_buffer_offset) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ExecuteIndirect");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_AtomicCopyBufferUINT(ID3D12GraphicsCommandList7 *This, ID3D12Resource *dst_buffer, UINT64 dst_offset, ID3D12Resource *src_buffer, UINT64 src_offset, UINT dependent_resource_count, ID3D12Resource *const *dependent_resources, const D3D12_SUBRESOURCE_RANGE_UINT64 *dependent_sub_resource_ranges) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "AtomicCopyBufferUINT");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_AtomicCopyBufferUINT64(ID3D12GraphicsCommandList7 *This, ID3D12Resource *dst_buffer, UINT64 dst_offset, ID3D12Resource *src_buffer, UINT64 src_offset, UINT dependent_resource_count, ID3D12Resource *const *dependent_resources, const D3D12_SUBRESOURCE_RANGE_UINT64 *dependent_sub_resource_ranges) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "AtomicCopyBufferUINT64");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_OMSetDepthBounds(ID3D12GraphicsCommandList7 *This, FLOAT min, FLOAT max) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "OMSetDepthBounds");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetSamplePositions(ID3D12GraphicsCommandList7 *This, UINT sample_count, UINT pixel_count, D3D12_SAMPLE_POSITION *sample_positions) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetSamplePositions");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ResolveSubresourceRegion(ID3D12GraphicsCommandList7 *This, ID3D12Resource *dst_resource, UINT dst_sub_resource_idx, UINT dst_x, UINT dst_y, ID3D12Resource *src_resource, UINT src_sub_resource_idx, D3D12_RECT *src_rect, DXGI_FORMAT format, D3D12_RESOLVE_MODE mode) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ResolveSubresourceRegion");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetViewInstanceMask(ID3D12GraphicsCommandList7 *This, UINT mask) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetViewInstanceMask");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_WriteBufferImmediate(ID3D12GraphicsCommandList7 *This, UINT count, const D3D12_WRITEBUFFERIMMEDIATE_PARAMETER *parameters, const D3D12_WRITEBUFFERIMMEDIATE_MODE *modes) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "WriteBufferImmediate");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetProtectedResourceSession(ID3D12GraphicsCommandList7 *This, ID3D12ProtectedResourceSession *protected_resource_session) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetProtectedResourceSession");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_BeginRenderPass(ID3D12GraphicsCommandList7 *This, UINT render_targets_count, const D3D12_RENDER_PASS_RENDER_TARGET_DESC *render_targets, const D3D12_RENDER_PASS_DEPTH_STENCIL_DESC *depth_stencil, D3D12_RENDER_PASS_FLAGS flags) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "BeginRenderPass");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_EndRenderPass(ID3D12GraphicsCommandList7 *This) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "EndRenderPass");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_InitializeMetaCommand(ID3D12GraphicsCommandList7 *This, ID3D12MetaCommand *meta_command, const void *initialization_parameters_data, SIZE_T initialization_parameters_data_size_in_bytes) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "InitializeMetaCommand");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_ExecuteMetaCommand(ID3D12GraphicsCommandList7 *This, ID3D12MetaCommand *meta_command, const void *execution_parameters_data, SIZE_T execution_parameters_data_size_in_bytes) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "ExecuteMetaCommand");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_BuildRaytracingAccelerationStructure(ID3D12GraphicsCommandList7 *This, const D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC *desc, UINT postbuild_info_descs_count, const D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC *postbuild_info_descs) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "BuildRaytracingAccelerationStructure");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_EmitRaytracingAccelerationStructurePostbuildInfo(ID3D12GraphicsCommandList7 *This, const D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC *desc, UINT src_acceleration_structures_count, const D3D12_GPU_VIRTUAL_ADDRESS *src_acceleration_structure_data) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "EmitRaytracingAccelerationStructurePostbuildInfo");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_CopyRaytracingAccelerationStructure(ID3D12GraphicsCommandList7 *This, D3D12_GPU_VIRTUAL_ADDRESS dst_acceleration_structure_data, D3D12_GPU_VIRTUAL_ADDRESS src_acceleration_structure_data, D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE mode) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "CopyRaytracingAccelerationStructure");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_SetPipelineState1(ID3D12GraphicsCommandList7 *This, ID3D12StateObject *state_object) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "SetPipelineState1");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_DispatchRays(ID3D12GraphicsCommandList7 *This, const D3D12_DISPATCH_RAYS_DESC *desc) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "DispatchRays");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_RSSetShadingRate(ID3D12GraphicsCommandList7 *This, D3D12_SHADING_RATE base_shading_rate, const D3D12_SHADING_RATE_COMBINER *combiners) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "RSSetShadingRate");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_RSSetShadingRateImage(ID3D12GraphicsCommandList7 *This, ID3D12Resource *shading_rate_image) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "RSSetShadingRateImage");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_DispatchMesh(ID3D12GraphicsCommandList7 *This, UINT thread_group_count_x, UINT thread_group_count_y, UINT thread_group_count_z) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "DispatchMesh");
}
static void STDMETHODCALLTYPE stub_ID3D12GraphicsCommandList7_Barrier(ID3D12GraphicsCommandList7 *This, UINT32 barrier_groups_count, const D3D12_BARRIER_GROUP *barrier_groups) {
    madeira_d3d12_note_unimplemented("ID3D12GraphicsCommandList7", "Barrier");
}

static void madeira_fill_ID3D12GraphicsCommandList7(ID3D12GraphicsCommandList7Vtbl *v) {
    v->QueryInterface = stub_ID3D12GraphicsCommandList7_QueryInterface;
    v->AddRef = stub_ID3D12GraphicsCommandList7_AddRef;
    v->Release = stub_ID3D12GraphicsCommandList7_Release;
    v->GetPrivateData = stub_ID3D12GraphicsCommandList7_GetPrivateData;
    v->SetPrivateData = stub_ID3D12GraphicsCommandList7_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12GraphicsCommandList7_SetPrivateDataInterface;
    v->SetName = stub_ID3D12GraphicsCommandList7_SetName;
    v->GetDevice = stub_ID3D12GraphicsCommandList7_GetDevice;
    v->GetType = stub_ID3D12GraphicsCommandList7_GetType;
    v->Close = stub_ID3D12GraphicsCommandList7_Close;
    v->Reset = stub_ID3D12GraphicsCommandList7_Reset;
    v->ClearState = stub_ID3D12GraphicsCommandList7_ClearState;
    v->DrawInstanced = stub_ID3D12GraphicsCommandList7_DrawInstanced;
    v->DrawIndexedInstanced = stub_ID3D12GraphicsCommandList7_DrawIndexedInstanced;
    v->Dispatch = stub_ID3D12GraphicsCommandList7_Dispatch;
    v->CopyBufferRegion = stub_ID3D12GraphicsCommandList7_CopyBufferRegion;
    v->CopyTextureRegion = stub_ID3D12GraphicsCommandList7_CopyTextureRegion;
    v->CopyResource = stub_ID3D12GraphicsCommandList7_CopyResource;
    v->CopyTiles = stub_ID3D12GraphicsCommandList7_CopyTiles;
    v->ResolveSubresource = stub_ID3D12GraphicsCommandList7_ResolveSubresource;
    v->IASetPrimitiveTopology = stub_ID3D12GraphicsCommandList7_IASetPrimitiveTopology;
    v->RSSetViewports = stub_ID3D12GraphicsCommandList7_RSSetViewports;
    v->RSSetScissorRects = stub_ID3D12GraphicsCommandList7_RSSetScissorRects;
    v->OMSetBlendFactor = stub_ID3D12GraphicsCommandList7_OMSetBlendFactor;
    v->OMSetStencilRef = stub_ID3D12GraphicsCommandList7_OMSetStencilRef;
    v->SetPipelineState = stub_ID3D12GraphicsCommandList7_SetPipelineState;
    v->ResourceBarrier = stub_ID3D12GraphicsCommandList7_ResourceBarrier;
    v->ExecuteBundle = stub_ID3D12GraphicsCommandList7_ExecuteBundle;
    v->SetDescriptorHeaps = stub_ID3D12GraphicsCommandList7_SetDescriptorHeaps;
    v->SetComputeRootSignature = stub_ID3D12GraphicsCommandList7_SetComputeRootSignature;
    v->SetGraphicsRootSignature = stub_ID3D12GraphicsCommandList7_SetGraphicsRootSignature;
    v->SetComputeRootDescriptorTable = stub_ID3D12GraphicsCommandList7_SetComputeRootDescriptorTable;
    v->SetGraphicsRootDescriptorTable = stub_ID3D12GraphicsCommandList7_SetGraphicsRootDescriptorTable;
    v->SetComputeRoot32BitConstant = stub_ID3D12GraphicsCommandList7_SetComputeRoot32BitConstant;
    v->SetGraphicsRoot32BitConstant = stub_ID3D12GraphicsCommandList7_SetGraphicsRoot32BitConstant;
    v->SetComputeRoot32BitConstants = stub_ID3D12GraphicsCommandList7_SetComputeRoot32BitConstants;
    v->SetGraphicsRoot32BitConstants = stub_ID3D12GraphicsCommandList7_SetGraphicsRoot32BitConstants;
    v->SetComputeRootConstantBufferView = stub_ID3D12GraphicsCommandList7_SetComputeRootConstantBufferView;
    v->SetGraphicsRootConstantBufferView = stub_ID3D12GraphicsCommandList7_SetGraphicsRootConstantBufferView;
    v->SetComputeRootShaderResourceView = stub_ID3D12GraphicsCommandList7_SetComputeRootShaderResourceView;
    v->SetGraphicsRootShaderResourceView = stub_ID3D12GraphicsCommandList7_SetGraphicsRootShaderResourceView;
    v->SetComputeRootUnorderedAccessView = stub_ID3D12GraphicsCommandList7_SetComputeRootUnorderedAccessView;
    v->SetGraphicsRootUnorderedAccessView = stub_ID3D12GraphicsCommandList7_SetGraphicsRootUnorderedAccessView;
    v->IASetIndexBuffer = stub_ID3D12GraphicsCommandList7_IASetIndexBuffer;
    v->IASetVertexBuffers = stub_ID3D12GraphicsCommandList7_IASetVertexBuffers;
    v->SOSetTargets = stub_ID3D12GraphicsCommandList7_SOSetTargets;
    v->OMSetRenderTargets = stub_ID3D12GraphicsCommandList7_OMSetRenderTargets;
    v->ClearDepthStencilView = stub_ID3D12GraphicsCommandList7_ClearDepthStencilView;
    v->ClearRenderTargetView = stub_ID3D12GraphicsCommandList7_ClearRenderTargetView;
    v->ClearUnorderedAccessViewUint = stub_ID3D12GraphicsCommandList7_ClearUnorderedAccessViewUint;
    v->ClearUnorderedAccessViewFloat = stub_ID3D12GraphicsCommandList7_ClearUnorderedAccessViewFloat;
    v->DiscardResource = stub_ID3D12GraphicsCommandList7_DiscardResource;
    v->BeginQuery = stub_ID3D12GraphicsCommandList7_BeginQuery;
    v->EndQuery = stub_ID3D12GraphicsCommandList7_EndQuery;
    v->ResolveQueryData = stub_ID3D12GraphicsCommandList7_ResolveQueryData;
    v->SetPredication = stub_ID3D12GraphicsCommandList7_SetPredication;
    v->SetMarker = stub_ID3D12GraphicsCommandList7_SetMarker;
    v->BeginEvent = stub_ID3D12GraphicsCommandList7_BeginEvent;
    v->EndEvent = stub_ID3D12GraphicsCommandList7_EndEvent;
    v->ExecuteIndirect = stub_ID3D12GraphicsCommandList7_ExecuteIndirect;
    v->AtomicCopyBufferUINT = stub_ID3D12GraphicsCommandList7_AtomicCopyBufferUINT;
    v->AtomicCopyBufferUINT64 = stub_ID3D12GraphicsCommandList7_AtomicCopyBufferUINT64;
    v->OMSetDepthBounds = stub_ID3D12GraphicsCommandList7_OMSetDepthBounds;
    v->SetSamplePositions = stub_ID3D12GraphicsCommandList7_SetSamplePositions;
    v->ResolveSubresourceRegion = stub_ID3D12GraphicsCommandList7_ResolveSubresourceRegion;
    v->SetViewInstanceMask = stub_ID3D12GraphicsCommandList7_SetViewInstanceMask;
    v->WriteBufferImmediate = stub_ID3D12GraphicsCommandList7_WriteBufferImmediate;
    v->SetProtectedResourceSession = stub_ID3D12GraphicsCommandList7_SetProtectedResourceSession;
    v->BeginRenderPass = stub_ID3D12GraphicsCommandList7_BeginRenderPass;
    v->EndRenderPass = stub_ID3D12GraphicsCommandList7_EndRenderPass;
    v->InitializeMetaCommand = stub_ID3D12GraphicsCommandList7_InitializeMetaCommand;
    v->ExecuteMetaCommand = stub_ID3D12GraphicsCommandList7_ExecuteMetaCommand;
    v->BuildRaytracingAccelerationStructure = stub_ID3D12GraphicsCommandList7_BuildRaytracingAccelerationStructure;
    v->EmitRaytracingAccelerationStructurePostbuildInfo = stub_ID3D12GraphicsCommandList7_EmitRaytracingAccelerationStructurePostbuildInfo;
    v->CopyRaytracingAccelerationStructure = stub_ID3D12GraphicsCommandList7_CopyRaytracingAccelerationStructure;
    v->SetPipelineState1 = stub_ID3D12GraphicsCommandList7_SetPipelineState1;
    v->DispatchRays = stub_ID3D12GraphicsCommandList7_DispatchRays;
    v->RSSetShadingRate = stub_ID3D12GraphicsCommandList7_RSSetShadingRate;
    v->RSSetShadingRateImage = stub_ID3D12GraphicsCommandList7_RSSetShadingRateImage;
    v->DispatchMesh = stub_ID3D12GraphicsCommandList7_DispatchMesh;
    v->Barrier = stub_ID3D12GraphicsCommandList7_Barrier;
}

/* ---- ID3D12Fence: 11 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_QueryInterface(ID3D12Fence *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12Fence", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12Fence_AddRef(ID3D12Fence *This) {
    madeira_d3d12_note_unimplemented("ID3D12Fence", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12Fence_Release(ID3D12Fence *This) {
    madeira_d3d12_note_unimplemented("ID3D12Fence", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_GetPrivateData(ID3D12Fence *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_SetPrivateData(ID3D12Fence *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_SetPrivateDataInterface(ID3D12Fence *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_SetName(ID3D12Fence *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_GetDevice(ID3D12Fence *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12Fence", "GetDevice");
    return E_NOTIMPL;
}
static UINT64 STDMETHODCALLTYPE stub_ID3D12Fence_GetCompletedValue(ID3D12Fence *This) {
    madeira_d3d12_note_unimplemented("ID3D12Fence", "GetCompletedValue");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_SetEventOnCompletion(ID3D12Fence *This, UINT64 value, HANDLE event) {
    madeira_d3d12_note_unimplemented("ID3D12Fence", "SetEventOnCompletion");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Fence_Signal(ID3D12Fence *This, UINT64 value) {
    madeira_d3d12_note_unimplemented("ID3D12Fence", "Signal");
    return E_NOTIMPL;
}

static void madeira_fill_ID3D12Fence(ID3D12FenceVtbl *v) {
    v->QueryInterface = stub_ID3D12Fence_QueryInterface;
    v->AddRef = stub_ID3D12Fence_AddRef;
    v->Release = stub_ID3D12Fence_Release;
    v->GetPrivateData = stub_ID3D12Fence_GetPrivateData;
    v->SetPrivateData = stub_ID3D12Fence_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12Fence_SetPrivateDataInterface;
    v->SetName = stub_ID3D12Fence_SetName;
    v->GetDevice = stub_ID3D12Fence_GetDevice;
    v->GetCompletedValue = stub_ID3D12Fence_GetCompletedValue;
    v->SetEventOnCompletion = stub_ID3D12Fence_SetEventOnCompletion;
    v->Signal = stub_ID3D12Fence_Signal;
}

/* ---- ID3D12Resource2: 17 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_QueryInterface(ID3D12Resource2 *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12Resource2_AddRef(ID3D12Resource2 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12Resource2_Release(ID3D12Resource2 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_GetPrivateData(ID3D12Resource2 *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_SetPrivateData(ID3D12Resource2 *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_SetPrivateDataInterface(ID3D12Resource2 *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_SetName(ID3D12Resource2 *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_GetDevice(ID3D12Resource2 *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "GetDevice");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_Map(ID3D12Resource2 *This, UINT sub_resource, const D3D12_RANGE *read_range, void **data) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "Map");
    return E_NOTIMPL;
}
static void STDMETHODCALLTYPE stub_ID3D12Resource2_Unmap(ID3D12Resource2 *This, UINT sub_resource, const D3D12_RANGE *written_range) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "Unmap");
}
static D3D12_RESOURCE_DESC * STDMETHODCALLTYPE stub_ID3D12Resource2_GetDesc(ID3D12Resource2 *This, D3D12_RESOURCE_DESC *__ret) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "GetDesc");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static D3D12_GPU_VIRTUAL_ADDRESS STDMETHODCALLTYPE stub_ID3D12Resource2_GetGPUVirtualAddress(ID3D12Resource2 *This) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "GetGPUVirtualAddress");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_WriteToSubresource(ID3D12Resource2 *This, UINT dst_sub_resource, const D3D12_BOX *dst_box, const void *src_data, UINT src_row_pitch, UINT src_slice_pitch) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "WriteToSubresource");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_ReadFromSubresource(ID3D12Resource2 *This, void *dst_data, UINT dst_row_pitch, UINT dst_slice_pitch, UINT src_sub_resource, const D3D12_BOX *src_box) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "ReadFromSubresource");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_GetHeapProperties(ID3D12Resource2 *This, D3D12_HEAP_PROPERTIES *heap_properties, D3D12_HEAP_FLAGS *flags) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "GetHeapProperties");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12Resource2_GetProtectedResourceSession(ID3D12Resource2 *This, REFIID riid, void **protected_session) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "GetProtectedResourceSession");
    return E_NOTIMPL;
}
static D3D12_RESOURCE_DESC1 * STDMETHODCALLTYPE stub_ID3D12Resource2_GetDesc1(ID3D12Resource2 *This, D3D12_RESOURCE_DESC1 *__ret) {
    madeira_d3d12_note_unimplemented("ID3D12Resource2", "GetDesc1");
    memset(__ret, 0, sizeof *__ret); return __ret;
}

static void madeira_fill_ID3D12Resource2(ID3D12Resource2Vtbl *v) {
    v->QueryInterface = stub_ID3D12Resource2_QueryInterface;
    v->AddRef = stub_ID3D12Resource2_AddRef;
    v->Release = stub_ID3D12Resource2_Release;
    v->GetPrivateData = stub_ID3D12Resource2_GetPrivateData;
    v->SetPrivateData = stub_ID3D12Resource2_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12Resource2_SetPrivateDataInterface;
    v->SetName = stub_ID3D12Resource2_SetName;
    v->GetDevice = stub_ID3D12Resource2_GetDevice;
    v->Map = stub_ID3D12Resource2_Map;
    v->Unmap = stub_ID3D12Resource2_Unmap;
    v->GetDesc = stub_ID3D12Resource2_GetDesc;
    v->GetGPUVirtualAddress = stub_ID3D12Resource2_GetGPUVirtualAddress;
    v->WriteToSubresource = stub_ID3D12Resource2_WriteToSubresource;
    v->ReadFromSubresource = stub_ID3D12Resource2_ReadFromSubresource;
    v->GetHeapProperties = stub_ID3D12Resource2_GetHeapProperties;
    v->GetProtectedResourceSession = stub_ID3D12Resource2_GetProtectedResourceSession;
    v->GetDesc1 = stub_ID3D12Resource2_GetDesc1;
}

/* ---- ID3D12RootSignature: 8 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12RootSignature_QueryInterface(ID3D12RootSignature *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12RootSignature", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12RootSignature_AddRef(ID3D12RootSignature *This) {
    madeira_d3d12_note_unimplemented("ID3D12RootSignature", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12RootSignature_Release(ID3D12RootSignature *This) {
    madeira_d3d12_note_unimplemented("ID3D12RootSignature", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12RootSignature_GetPrivateData(ID3D12RootSignature *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12RootSignature_SetPrivateData(ID3D12RootSignature *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12RootSignature_SetPrivateDataInterface(ID3D12RootSignature *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12RootSignature_SetName(ID3D12RootSignature *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12RootSignature_GetDevice(ID3D12RootSignature *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12RootSignature", "GetDevice");
    return E_NOTIMPL;
}

static void madeira_fill_ID3D12RootSignature(ID3D12RootSignatureVtbl *v) {
    v->QueryInterface = stub_ID3D12RootSignature_QueryInterface;
    v->AddRef = stub_ID3D12RootSignature_AddRef;
    v->Release = stub_ID3D12RootSignature_Release;
    v->GetPrivateData = stub_ID3D12RootSignature_GetPrivateData;
    v->SetPrivateData = stub_ID3D12RootSignature_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12RootSignature_SetPrivateDataInterface;
    v->SetName = stub_ID3D12RootSignature_SetName;
    v->GetDevice = stub_ID3D12RootSignature_GetDevice;
}

/* ---- ID3D12PipelineState: 9 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12PipelineState_QueryInterface(ID3D12PipelineState *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12PipelineState", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12PipelineState_AddRef(ID3D12PipelineState *This) {
    madeira_d3d12_note_unimplemented("ID3D12PipelineState", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12PipelineState_Release(ID3D12PipelineState *This) {
    madeira_d3d12_note_unimplemented("ID3D12PipelineState", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12PipelineState_GetPrivateData(ID3D12PipelineState *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12PipelineState_SetPrivateData(ID3D12PipelineState *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12PipelineState_SetPrivateDataInterface(ID3D12PipelineState *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12PipelineState_SetName(ID3D12PipelineState *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12PipelineState_GetDevice(ID3D12PipelineState *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12PipelineState", "GetDevice");
    return E_NOTIMPL;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12PipelineState_GetCachedBlob(ID3D12PipelineState *This, ID3DBlob **blob) {
    madeira_d3d12_note_unimplemented("ID3D12PipelineState", "GetCachedBlob");
    return E_NOTIMPL;
}

static void madeira_fill_ID3D12PipelineState(ID3D12PipelineStateVtbl *v) {
    v->QueryInterface = stub_ID3D12PipelineState_QueryInterface;
    v->AddRef = stub_ID3D12PipelineState_AddRef;
    v->Release = stub_ID3D12PipelineState_Release;
    v->GetPrivateData = stub_ID3D12PipelineState_GetPrivateData;
    v->SetPrivateData = stub_ID3D12PipelineState_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12PipelineState_SetPrivateDataInterface;
    v->SetName = stub_ID3D12PipelineState_SetName;
    v->GetDevice = stub_ID3D12PipelineState_GetDevice;
    v->GetCachedBlob = stub_ID3D12PipelineState_GetCachedBlob;
}

/* ---- ID3D12DescriptorHeap: 11 slots ---- */
static HRESULT STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_QueryInterface(ID3D12DescriptorHeap *This, REFIID riid, void **ppvObject) {
    madeira_d3d12_note_unimplemented("ID3D12DescriptorHeap", "QueryInterface");
    return E_NOTIMPL;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_AddRef(ID3D12DescriptorHeap *This) {
    madeira_d3d12_note_unimplemented("ID3D12DescriptorHeap", "AddRef");
    return 0;
}
static ULONG STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_Release(ID3D12DescriptorHeap *This) {
    madeira_d3d12_note_unimplemented("ID3D12DescriptorHeap", "Release");
    return 0;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_GetPrivateData(ID3D12DescriptorHeap *This, REFGUID guid, UINT *data_size, void *data) {
    return mad_pd_get(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_SetPrivateData(ID3D12DescriptorHeap *This, REFGUID guid, UINT data_size, const void *data) {
    return mad_pd_set(This, guid, data_size, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_SetPrivateDataInterface(ID3D12DescriptorHeap *This, REFGUID guid, const IUnknown *data) {
    return mad_pd_set_iface(This, guid, data);
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_SetName(ID3D12DescriptorHeap *This, const WCHAR *name) {
    return S_OK;
}
static HRESULT STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_GetDevice(ID3D12DescriptorHeap *This, REFIID riid, void **device) {
    madeira_d3d12_note_unimplemented("ID3D12DescriptorHeap", "GetDevice");
    return E_NOTIMPL;
}
static D3D12_DESCRIPTOR_HEAP_DESC * STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_GetDesc(ID3D12DescriptorHeap *This, D3D12_DESCRIPTOR_HEAP_DESC *__ret) {
    madeira_d3d12_note_unimplemented("ID3D12DescriptorHeap", "GetDesc");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static D3D12_CPU_DESCRIPTOR_HANDLE * STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart(ID3D12DescriptorHeap *This, D3D12_CPU_DESCRIPTOR_HANDLE *__ret) {
    madeira_d3d12_note_unimplemented("ID3D12DescriptorHeap", "GetCPUDescriptorHandleForHeapStart");
    memset(__ret, 0, sizeof *__ret); return __ret;
}
static D3D12_GPU_DESCRIPTOR_HANDLE * STDMETHODCALLTYPE stub_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart(ID3D12DescriptorHeap *This, D3D12_GPU_DESCRIPTOR_HANDLE *__ret) {
    madeira_d3d12_note_unimplemented("ID3D12DescriptorHeap", "GetGPUDescriptorHandleForHeapStart");
    memset(__ret, 0, sizeof *__ret); return __ret;
}

static void madeira_fill_ID3D12DescriptorHeap(ID3D12DescriptorHeapVtbl *v) {
    v->QueryInterface = stub_ID3D12DescriptorHeap_QueryInterface;
    v->AddRef = stub_ID3D12DescriptorHeap_AddRef;
    v->Release = stub_ID3D12DescriptorHeap_Release;
    v->GetPrivateData = stub_ID3D12DescriptorHeap_GetPrivateData;
    v->SetPrivateData = stub_ID3D12DescriptorHeap_SetPrivateData;
    v->SetPrivateDataInterface = stub_ID3D12DescriptorHeap_SetPrivateDataInterface;
    v->SetName = stub_ID3D12DescriptorHeap_SetName;
    v->GetDevice = stub_ID3D12DescriptorHeap_GetDevice;
    v->GetDesc = stub_ID3D12DescriptorHeap_GetDesc;
    v->GetCPUDescriptorHandleForHeapStart = stub_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart;
    v->GetGPUDescriptorHandleForHeapStart = stub_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart;
}

#endif /* MADEIRA_D3D12_STUBS_H */
